# Advanced NLP Assignment 3

## Q1

**(1)**
 Explain three different points between P-Tuning V1 and P-Tuning V2.
 

- **Prompt depth**: P-Tuning V1 only adds continuous prompts to the input layer of the pre-trained model, while P-Tuning V2 adds prompts to every layer of the model. This increases the capacity and impact of the prompts.
- **Classification head**: P-Tuning V1 uses a language modeling head to predict verbalizers, which are natural language tokens that correspond to labels. P-Tuning V2 uses a linear classifier on top of the [CLS] token or the target tokens, which is simpler and more compatible with sequence labeling tasks.
- **Reparameterization**: P-Tuning V1 always uses a reparameterization encoder such as an MLP to transform the trainable embeddings. P-Tuning V2 finds that the usefulness of reparameterization depends on the tasks and datasets, and sometimes a simple embedding layer is enough.

**(2)**
 Write code to finetune Tiny-BERT with P-Tuning v2 method using the MRPC Dataset.


In [1]:
# !python -m pip install --user --upgrade evaluate

In [2]:
from transformers import AutoTokenizer, AutoModelForSequenceClassification, TrainingArguments, Trainer
from datasets import load_dataset, load_metric
from peft import get_peft_config, get_peft_model, PrefixTuningConfig, TaskType, PeftType

import torch
import transformers
import numpy as np
import evaluate
import warnings

warnings.simplefilter("ignore")

global_metric = load_metric("./accuracy/accuracy.py")

# Load the MRPC dataset
dataset = load_dataset(
    path = "json", 
    data_dir = "./Q1_MRPC_dataset", 
    data_files = {"train": "train.jsonl", "test": "test.jsonl", "validation": "validation.jsonl"}
)

# Load the Tiny-BERT model
model_dir = "./Q1_model_checkpoint_tinybert/"
tokenizer = AutoTokenizer.from_pretrained(model_dir)
print(tokenizer)
model = AutoModelForSequenceClassification.from_pretrained(model_dir, num_labels=2)
# peft_config = PrefixTuningConfig(task_type="SEQ_CLS", num_virtual_tokens=10, prefix_projection=True)
peft_config = PrefixTuningConfig(task_type=TaskType.SEQ_CLS, num_virtual_tokens=5, prefix_projection=True)
model = get_peft_model(model, peft_config)

# Tokenize the dataset
def tokenize_function(example):
    return tokenizer(example["text1"], example["text2"], padding=True, truncation=True, max_length=128)

tokenized_dataset = dataset.map(tokenize_function, batched=True)

# Print the first tokenized example
# print(tokenized_dataset["train"][0])

# Define the optimizer and the learning rate scheduler
optimizer = torch.optim.AdamW(model.parameters(), lr=1e-3)
scheduler = transformers.get_linear_schedule_with_warmup(optimizer, num_warmup_steps=0, num_training_steps=len(dataset["train"]) * 3)

# Define the training arguments
training_args = TrainingArguments(
    output_dir="./results",
    evaluation_strategy="epoch",
    save_strategy="epoch",
    learning_rate=1e-3,
    per_device_train_batch_size=16,
    per_device_eval_batch_size=64,
    num_train_epochs=3,
    weight_decay=0.71,
    push_to_hub=False,
    logging_dir="./logs",
    logging_steps=10,
    load_best_model_at_end=True,
    metric_for_best_model="accuracy",
    greater_is_better=True,
)

# Define the training and evaluation functions
def compute_metrics(eval_preds):
#     metric = load_metric("accuracy")
#     metric = evaluate.load("accuracy")
    metric = global_metric
    logits, labels = eval_preds
    predictions = np.argmax(logits, axis=-1)
    print(logits)
    return metric.compute(predictions=predictions, references=labels)

def m_train():
    trainer = Trainer(
        model=model,
        args=training_args,
        train_dataset=tokenized_dataset["train"],
        eval_dataset=tokenized_dataset["validation"],
        data_collator=None,
        tokenizer=tokenizer,
        compute_metrics=compute_metrics,
    )
    trainer.train()
    

# def m_evaluate():
#     trainer = Trainer(
#         model=model,
#         args=training_args,
#         train_dataset=None,
#         eval_dataset=tokenized_dataset["validation"],
#         data_collator=None,
#         tokenizer=tokenizer,
#         compute_metrics=compute_metrics,
#     )
#     result = trainer.evaluate()
#     return result
    
print(dataset["train"])
    
    
# Train the model
m_train()

# # Evaluate the model
# m_evaluate()


C:\Users\Wandering Troubadour\AppData\Roaming\Python\Python310\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Some weights of BertForSequenceClassification were not initialized from the model checkpoint at ./Q1_model_checkpoint_tinybert/ and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


BertTokenizerFast(name_or_path='./Q1_model_checkpoint_tinybert/', vocab_size=30522, model_max_length=1000000000000000019884624838656, is_fast=True, padding_side='right', truncation_side='right', special_tokens={'unk_token': '[UNK]', 'sep_token': '[SEP]', 'pad_token': '[PAD]', 'cls_token': '[CLS]', 'mask_token': '[MASK]'}, clean_up_tokenization_spaces=True),  added_tokens_decoder={
	0: AddedToken("[PAD]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	100: AddedToken("[UNK]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	101: AddedToken("[CLS]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	102: AddedToken("[SEP]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	103: AddedToken("[MASK]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
}


You're using a BertTokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.


Dataset({
    features: ['text1', 'text2', 'label', 'idx', 'label_text'],
    num_rows: 3668
})


[[-0.09249687  0.11540358]
 [-0.09352325  0.11496075]
 [-0.09063625  0.11420518]
 [-0.09036144  0.11408391]
 [-0.08730927  0.1147303 ]
 [-0.0916579   0.11519246]
 [-0.09237979  0.11412458]
 [-0.09238221  0.11194103]
 [-0.09151222  0.1134225 ]
 [-0.089879    0.11069457]
 [-0.09224872  0.11394204]
 [-0.09397955  0.11598086]
 [-0.09024739  0.11283821]
 [-0.08794298  0.11377968]
 [-0.08930318  0.11311269]
 [-0.0914993   0.11481065]
 [-0.09080354  0.11547096]
 [-0.09030809  0.1126959 ]
 [-0.09179223  0.11333272]
 [-0.09081797  0.11479351]
 [-0.08974633  0.11416266]
 [-0.09115393  0.11237532]
 [-0.09070686  0.11441605]
 [-0.08933958  0.11631729]
 [-0.09175996  0.11462677]
 [-0.08477257  0.11094671]
 [-0.09257574  0.11523549]
 [-0.09375988  0.11613418]
 [-0.09270996  0.11457253]
 [-0.09143996  0.11266536]
 [-0.09082658  0.11432387]
 [-0.0929966   0.11692114]
 [-0.09149681  0.11491474]
 [-0.09196886  0.11305641]
 [-0.09181958  0.11323889]
 [-0.09300733  0.11580278]
 [-0.08929977  0.11361894]
 

[[-0.18038802  0.20164686]
 [-0.18167436  0.20111609]
 [-0.17909145  0.20232205]
 [-0.18058448  0.20320854]
 [-0.17737901  0.2008692 ]
 [-0.18065597  0.20300433]
 [-0.18027586  0.20078936]
 [-0.18183663  0.20198092]
 [-0.18003133  0.20141655]
 [-0.18210804  0.20335825]
 [-0.17995992  0.20233838]
 [-0.18008968  0.20123285]
 [-0.18015134  0.20219874]
 [-0.17934349  0.20359738]
 [-0.1808492   0.20435643]
 [-0.1823611   0.20420979]
 [-0.18041871  0.20347631]
 [-0.17979442  0.20205149]
 [-0.18080568  0.20269772]
 [-0.18107264  0.20381661]
 [-0.18031749  0.20343713]
 [-0.1803772   0.20176655]
 [-0.18253145  0.20386113]
 [-0.18053953  0.2067067 ]
 [-0.17947891  0.20318657]
 [-0.18014103  0.20404533]
 [-0.17983353  0.20160301]
 [-0.1796957   0.20095927]
 [-0.18049136  0.20196837]
 [-0.18149084  0.2025984 ]
 [-0.18058074  0.20293759]
 [-0.18124133  0.20451322]
 [-0.17962694  0.20116565]
 [-0.18095809  0.20225415]
 [-0.1816054   0.20295748]
 [-0.18000306  0.20180644]
 [-0.18058792  0.20510371]
 

[[-0.18985637  0.2139124 ]
 [-0.19070919  0.21475019]
 [-0.18969025  0.21442373]
 [-0.18933733  0.21381767]
 [-0.19014966  0.21570489]
 [-0.18740876  0.21226595]
 [-0.19027624  0.21474643]
 [-0.18815662  0.21136124]
 [-0.18855996  0.21306695]
 [-0.19030483  0.21445064]
 [-0.19029446  0.21528311]
 [-0.1918463   0.21560557]
 [-0.18812127  0.21239682]
 [-0.18880907  0.21424359]
 [-0.1890523   0.21461509]
 [-0.18776666  0.21303298]
 [-0.19056083  0.21473992]
 [-0.18842818  0.21281601]
 [-0.1898835   0.21403992]
 [-0.18787894  0.21234827]
 [-0.18867971  0.21308272]
 [-0.18966691  0.2128644 ]
 [-0.18969308  0.2138979 ]
 [-0.1876676   0.21387576]
 [-0.18970211  0.21470572]
 [-0.18589576  0.21219915]
 [-0.18967742  0.21428809]
 [-0.19361067  0.21679853]
 [-0.18907876  0.21377446]
 [-0.1886562   0.21226074]
 [-0.18944182  0.21331754]
 [-0.19061054  0.21521649]
 [-0.19090536  0.2152702 ]
 [-0.1873515   0.21177547]
 [-0.1902368   0.21414757]
 [-0.18997593  0.2139924 ]
 [-0.18959863  0.214678  ]
 

[[-0.26416293  0.28468686]
 [-0.26315698  0.28272897]
 [-0.26347917  0.28441635]
 [-0.26391217  0.2847165 ]
 [-0.26154086  0.2828083 ]
 [-0.26571405  0.2870998 ]
 [-0.26371932  0.28343242]
 [-0.26542225  0.2858402 ]
 [-0.26479998  0.28574112]
 [-0.264583    0.28510606]
 [-0.26443294  0.2858921 ]
 [-0.2634789   0.28332752]
 [-0.2626886   0.2816512 ]
 [-0.26263207  0.28406888]
 [-0.26412532  0.28528214]
 [-0.26559776  0.2864351 ]
 [-0.26489785  0.286224  ]
 [-0.26268506  0.28187603]
 [-0.26467574  0.2848997 ]
 [-0.26459944  0.28555357]
 [-0.26286393  0.282843  ]
 [-0.26407248  0.28400916]
 [-0.26453012  0.28517634]
 [-0.2642789   0.2859983 ]
 [-0.26414946  0.28590852]
 [-0.26427943  0.28565598]
 [-0.26251295  0.28263003]
 [-0.26330897  0.28299004]
 [-0.26403633  0.28507918]
 [-0.26425305  0.28405178]
 [-0.26462302  0.2854525 ]
 [-0.26372615  0.28443223]
 [-0.26197806  0.28242493]
 [-0.2651526   0.2856024 ]
 [-0.26374748  0.28456968]
 [-0.26419422  0.2852568 ]
 [-0.2632338   0.28426188]
 

[[-0.3313238   0.35693288]
 [-0.3334082   0.35896945]
 [-0.33209234  0.3591486 ]
 [-0.33329883  0.35919678]
 [-0.33307168  0.35882595]
 [-0.3320778   0.3583989 ]
 [-0.33271822  0.35873812]
 [-0.332219    0.3570155 ]
 [-0.33231738  0.35846812]
 [-0.3313371   0.3579157 ]
 [-0.33021665  0.35712448]
 [-0.33305487  0.35855687]
 [-0.33308575  0.35860193]
 [-0.33350998  0.36068714]
 [-0.33192492  0.3591051 ]
 [-0.33362737  0.3592512 ]
 [-0.3317413   0.3585618 ]
 [-0.33264166  0.3587149 ]
 [-0.33162034  0.35765272]
 [-0.33238196  0.35863462]
 [-0.33186644  0.35804945]
 [-0.33244097  0.35779437]
 [-0.3317345   0.35823095]
 [-0.33088136  0.35931188]
 [-0.33030808  0.3581239 ]
 [-0.3329524   0.35877252]
 [-0.3335212   0.35916305]
 [-0.3327972   0.3591336 ]
 [-0.33227462  0.35884213]
 [-0.3334655   0.3587941 ]
 [-0.33131158  0.35749978]
 [-0.33093056  0.35754964]
 [-0.33252126  0.3586669 ]
 [-0.33273637  0.35807878]
 [-0.3321779   0.35883248]
 [-0.33283544  0.35820064]
 [-0.33238173  0.36001217]
 

[[-0.35202694  0.37435126]
 [-0.3506169   0.37411746]
 [-0.35166514  0.37641641]
 [-0.35090533  0.37434423]
 [-0.34965602  0.37216753]
 [-0.35064334  0.3752783 ]
 [-0.34993446  0.37363055]
 [-0.35126787  0.3737222 ]
 [-0.35120964  0.37510073]
 [-0.35287288  0.3764284 ]
 [-0.35202786  0.3756944 ]
 [-0.35184446  0.3748681 ]
 [-0.35195148  0.37518382]
 [-0.34990957  0.37500274]
 [-0.3506106   0.37507296]
 [-0.35088512  0.3741053 ]
 [-0.34981194  0.37430042]
 [-0.3519588   0.37584373]
 [-0.35295597  0.3763826 ]
 [-0.35118547  0.3759415 ]
 [-0.35085726  0.37443882]
 [-0.3500185   0.37366468]
 [-0.35155097  0.37569007]
 [-0.35085934  0.37726885]
 [-0.35048032  0.37551445]
 [-0.3486837   0.3728088 ]
 [-0.3510794   0.37404868]
 [-0.3516646   0.37565106]
 [-0.35198903  0.37533253]
 [-0.35175836  0.37534195]
 [-0.3501048   0.37469167]
 [-0.35144594  0.375282  ]
 [-0.3519212   0.3753192 ]
 [-0.35142452  0.37455067]
 [-0.35181284  0.3754402 ]
 [-0.35081476  0.37445104]
 [-0.35137397  0.3763781 ]
 

[[-0.3237097   0.33978933]
 [-0.32075617  0.3366402 ]
 [-0.32207164  0.33815026]
 [-0.3209963   0.3369784 ]
 [-0.32136706  0.3379093 ]
 [-0.32109722  0.33732912]
 [-0.32154438  0.33792898]
 [-0.32132593  0.33593073]
 [-0.3212749   0.33694008]
 [-0.3239908   0.34041825]
 [-0.32197997  0.33746412]
 [-0.3228432   0.33870238]
 [-0.32205757  0.33788624]
 [-0.32042718  0.33662823]
 [-0.32311037  0.34017876]
 [-0.3216687   0.33782384]
 [-0.321025    0.33680978]
 [-0.32282564  0.33901533]
 [-0.32459712  0.3406965 ]
 [-0.32173628  0.33812886]
 [-0.3230407   0.3393468 ]
 [-0.3202975   0.33583218]
 [-0.32372028  0.34054706]
 [-0.32202536  0.3391086 ]
 [-0.32009932  0.3362222 ]
 [-0.32097012  0.33780882]
 [-0.3217167   0.33755484]
 [-0.3226006   0.33889845]
 [-0.32162002  0.33742663]
 [-0.3204458   0.33542684]
 [-0.32216343  0.33830312]
 [-0.3235582   0.3397039 ]
 [-0.32219335  0.33865   ]
 [-0.32174298  0.33712408]
 [-0.32006466  0.33617708]
 [-0.32029048  0.33599192]
 [-0.32102218  0.33734167]
 

[[-0.2146508   0.223361  ]
 [-0.2135739   0.22223978]
 [-0.21145883  0.22035977]
 [-0.21324137  0.22185709]
 [-0.21250197  0.2215044 ]
 [-0.21303625  0.22191752]
 [-0.21306615  0.22196408]
 [-0.2117064   0.21941648]
 [-0.21193337  0.22070602]
 [-0.21335997  0.22192635]
 [-0.21349052  0.2216546 ]
 [-0.21376611  0.22231783]
 [-0.21169576  0.22045355]
 [-0.21114321  0.22035217]
 [-0.21373327  0.22254862]
 [-0.21347572  0.22214489]
 [-0.21329038  0.22183447]
 [-0.21233176  0.22115028]
 [-0.21269074  0.22086857]
 [-0.21262749  0.22153397]
 [-0.21357359  0.22257434]
 [-0.21204644  0.22058974]
 [-0.21354829  0.22274218]
 [-0.21284431  0.22220744]
 [-0.21273065  0.22150135]
 [-0.21224174  0.22175318]
 [-0.21284027  0.22139056]
 [-0.21307188  0.22178896]
 [-0.21293117  0.22133024]
 [-0.21127318  0.21965438]
 [-0.21240662  0.2209524 ]
 [-0.21436466  0.22290553]
 [-0.21397734  0.22308294]
 [-0.21225683  0.22049738]
 [-0.2125465   0.22117867]
 [-0.21184595  0.22054923]
 [-0.21305092  0.22214119]
 

[[-0.3680965   0.40291497]
 [-0.36681455  0.40193686]
 [-0.36671346  0.40216076]
 [-0.36743575  0.40241018]
 [-0.3671817   0.40218592]
 [-0.36711383  0.4021328 ]
 [-0.36679745  0.40207702]
 [-0.36654067  0.4009605 ]
 [-0.36757416  0.40235263]
 [-0.36693057  0.40146297]
 [-0.36788324  0.4024614 ]
 [-0.36792415  0.4032277 ]
 [-0.36657155  0.4020577 ]
 [-0.3664962   0.40181166]
 [-0.36682552  0.40184993]
 [-0.367141    0.40219843]
 [-0.36709604  0.40203303]
 [-0.3656075   0.4014768 ]
 [-0.3679514   0.40258208]
 [-0.36665335  0.40194234]
 [-0.3674127   0.40239197]
 [-0.36621135  0.40138334]
 [-0.36724246  0.4023505 ]
 [-0.36661583  0.40223515]
 [-0.36756968  0.4027622 ]
 [-0.36609447  0.40145263]
 [-0.36684072  0.40175086]
 [-0.3678125   0.4028892 ]
 [-0.36694396  0.4020911 ]
 [-0.36597416  0.40131724]
 [-0.36707616  0.40203005]
 [-0.36812624  0.40303558]
 [-0.3676356   0.40251255]
 [-0.3670684   0.40185165]
 [-0.36735016  0.4023319 ]
 [-0.36724025  0.40242618]
 [-0.3662415   0.40157744]
 

[[-0.4094541   0.44468993]
 [-0.4079392   0.4436953 ]
 [-0.4064659   0.4424066 ]
 [-0.40800798  0.44362038]
 [-0.40789646  0.44354236]
 [-0.40779036  0.4437073 ]
 [-0.4069509   0.4428119 ]
 [-0.40745255  0.44295746]
 [-0.4086867   0.44420588]
 [-0.40805072  0.44355017]
 [-0.40735465  0.44291246]
 [-0.4088487   0.44445705]
 [-0.4066645   0.44262534]
 [-0.40706277  0.44297993]
 [-0.4074161   0.44312197]
 [-0.40809333  0.44381142]
 [-0.4068451   0.44260848]
 [-0.40611583  0.44221675]
 [-0.40807563  0.44355404]
 [-0.40734082  0.44315892]
 [-0.4086366   0.44398928]
 [-0.40612754  0.44206142]
 [-0.40829724  0.4439742 ]
 [-0.4059524   0.44224417]
 [-0.40731466  0.44316238]
 [-0.40790403  0.44358617]
 [-0.40873998  0.444354  ]
 [-0.40814158  0.4437191 ]
 [-0.40775955  0.44359195]
 [-0.40674853  0.4427353 ]
 [-0.4076125   0.44314802]
 [-0.40833306  0.44381398]
 [-0.40843937  0.44394708]
 [-0.40753335  0.44320697]
 [-0.40796667  0.44366628]
 [-0.40737635  0.44317794]
 [-0.40757287  0.44350743]
 

[[-0.33231384  0.3595059 ]
 [-0.3313647   0.35901806]
 [-0.3287416   0.35672572]
 [-0.3307099   0.35840502]
 [-0.33125076  0.35892406]
 [-0.32982704  0.35788566]
 [-0.32978535  0.35767984]
 [-0.33008876  0.3574532 ]
 [-0.33072588  0.3583679 ]
 [-0.33027214  0.35776713]
 [-0.3306714   0.35820493]
 [-0.33222     0.3599389 ]
 [-0.32795325  0.35602438]
 [-0.33014795  0.35808024]
 [-0.33017704  0.3579735 ]
 [-0.33077893  0.35841736]
 [-0.3295084   0.35735336]
 [-0.32786557  0.35599992]
 [-0.33104062  0.3583847 ]
 [-0.32949772  0.35737845]
 [-0.33116472  0.35855964]
 [-0.32866433  0.35675177]
 [-0.33106735  0.3587754 ]
 [-0.32888898  0.35726655]
 [-0.3303319   0.35824922]
 [-0.3310277   0.35866997]
 [-0.33211312  0.35957322]
 [-0.33168712  0.3593301 ]
 [-0.33033827  0.35810718]
 [-0.32865283  0.35668662]
 [-0.3305218   0.35812768]
 [-0.33186778  0.35933894]
 [-0.3314814   0.35893378]
 [-0.3294129   0.35724825]
 [-0.33090222  0.35861513]
 [-0.33045903  0.3581533 ]
 [-0.3314112   0.3593125 ]
 

[[-0.48140585  0.5130992 ]
 [-0.4813648   0.51340896]
 [-0.48158568  0.51355547]
 [-0.48144698  0.513297  ]
 [-0.48158327  0.5134476 ]
 [-0.4813155   0.5134294 ]
 [-0.48118252  0.5130376 ]
 [-0.4820394   0.51394606]
 [-0.48145908  0.51318806]
 [-0.4818811   0.5137934 ]
 [-0.48191136  0.51373017]
 [-0.4814849   0.5132653 ]
 [-0.48134127  0.5132011 ]
 [-0.48149475  0.51353735]
 [-0.481486    0.51341975]
 [-0.4817748   0.5136555 ]
 [-0.4817041   0.5135499 ]
 [-0.48133618  0.51317716]
 [-0.48166424  0.5135807 ]
 [-0.48122263  0.51324236]
 [-0.48146412  0.5131844 ]
 [-0.4813786   0.5132907 ]
 [-0.48151624  0.5136491 ]
 [-0.4817217   0.51401883]
 [-0.48153973  0.5135858 ]
 [-0.48204586  0.51392555]
 [-0.48135543  0.51325935]
 [-0.48129648  0.51320374]
 [-0.4814614   0.51348364]
 [-0.48144564  0.5133828 ]
 [-0.4817438   0.5136657 ]
 [-0.48157084  0.5135707 ]
 [-0.48134336  0.5131454 ]
 [-0.48147783  0.51335424]
 [-0.48166037  0.51374453]
 [-0.48164135  0.5136704 ]
 [-0.4818577   0.51372445]
 

[[-0.27623153  0.29692727]
 [-0.27590516  0.29668197]
 [-0.27624172  0.29706484]
 [-0.27598497  0.29669333]
 [-0.27624747  0.2969225 ]
 [-0.27616045  0.29706037]
 [-0.2761883   0.29692402]
 [-0.276402    0.29722628]
 [-0.2763837   0.29712752]
 [-0.27617723  0.2969271 ]
 [-0.2763598   0.2971233 ]
 [-0.2761597   0.29683998]
 [-0.27616942  0.29687816]
 [-0.2760392   0.29690862]
 [-0.27610436  0.29692328]
 [-0.27623644  0.2969603 ]
 [-0.27625558  0.29705855]
 [-0.2759676   0.29667726]
 [-0.276208    0.29701442]
 [-0.27614737  0.29698396]
 [-0.2762181   0.29687217]
 [-0.27622557  0.29707462]
 [-0.27617848  0.29697767]
 [-0.27611214  0.29700056]
 [-0.27638862  0.2971744 ]
 [-0.2764809   0.29725307]
 [-0.2758115   0.2965528 ]
 [-0.27584833  0.29654825]
 [-0.27597874  0.2967816 ]
 [-0.27629662  0.29714042]
 [-0.27619877  0.29700598]
 [-0.27611294  0.2969026 ]
 [-0.27604356  0.29675114]
 [-0.2762937   0.29703826]
 [-0.27624518  0.2969963 ]
 [-0.27608502  0.29688042]
 [-0.27619117  0.29691523]
 

[[-0.26887864  0.29147333]
 [-0.26873013  0.29138368]
 [-0.26899636  0.29166648]
 [-0.26871324  0.29131627]
 [-0.26902688  0.29158637]
 [-0.2687763   0.29152972]
 [-0.26888198  0.2914946 ]
 [-0.2689689   0.2916469 ]
 [-0.26899904  0.2916219 ]
 [-0.268801    0.29142112]
 [-0.26888195  0.29155558]
 [-0.26890555  0.29147622]
 [-0.2688728   0.29143825]
 [-0.26878217  0.29151833]
 [-0.26879534  0.29150087]
 [-0.26901454  0.29162884]
 [-0.26903418  0.29171216]
 [-0.26877752  0.2913543 ]
 [-0.26885274  0.29153228]
 [-0.26888403  0.2915513 ]
 [-0.26892397  0.29147768]
 [-0.26891005  0.2916136 ]
 [-0.26882315  0.29151827]
 [-0.26887298  0.29161996]
 [-0.26901516  0.2917084 ]
 [-0.2690182   0.29168802]
 [-0.2686065   0.29122305]
 [-0.26869348  0.29129457]
 [-0.2686605   0.2913579 ]
 [-0.26891276  0.29162323]
 [-0.26888284  0.29155585]
 [-0.2688109   0.2914834 ]
 [-0.268796    0.29141486]
 [-0.2688863   0.2915208 ]
 [-0.2688559   0.2914928 ]
 [-0.26877952  0.2914552 ]
 [-0.26894265  0.2915972 ]
 

[[-0.3722142   0.40430856]
 [-0.37205458  0.40421715]
 [-0.37226236  0.40447396]
 [-0.3719557   0.40404707]
 [-0.37223262  0.40430143]
 [-0.37215006  0.40439576]
 [-0.37215889  0.40426064]
 [-0.37224105  0.40443057]
 [-0.37231207  0.40442824]
 [-0.37191033  0.40403026]
 [-0.37207657  0.4042726 ]
 [-0.37218195  0.40426356]
 [-0.37219474  0.40423965]
 [-0.37205154  0.40430534]
 [-0.37186393  0.4040578 ]
 [-0.3722843   0.40440303]
 [-0.37227812  0.40445906]
 [-0.37216082  0.40422884]
 [-0.37203273  0.40424007]
 [-0.37222746  0.40439194]
 [-0.37218425  0.40424782]
 [-0.37225     0.40444285]
 [-0.37213254  0.4043454 ]
 [-0.3721011   0.40434352]
 [-0.37225795  0.40449387]
 [-0.37232673  0.40452614]
 [-0.37179393  0.40390834]
 [-0.3719836   0.40410113]
 [-0.37184954  0.40404817]
 [-0.37222266  0.4044202 ]
 [-0.37224126  0.40441626]
 [-0.37205762  0.4042529 ]
 [-0.37194562  0.40407825]
 [-0.37227213  0.40440518]
 [-0.37211657  0.40427738]
 [-0.37199187  0.4041816 ]
 [-0.372091    0.40423965]
 

[[-0.46656972  0.5032007 ]
 [-0.4665205   0.5032629 ]
 [-0.46646476  0.50321674]
 [-0.46646357  0.5031346 ]
 [-0.46647757  0.50311947]
 [-0.46662855  0.50342506]
 [-0.46645182  0.5031094 ]
 [-0.46662295  0.50333   ]
 [-0.46661252  0.5032343 ]
 [-0.4663481   0.5030111 ]
 [-0.46641147  0.50313693]
 [-0.4665203   0.5031495 ]
 [-0.4665727   0.50316685]
 [-0.4664213   0.5032529 ]
 [-0.46616787  0.502956  ]
 [-0.4665063   0.5031994 ]
 [-0.46649975  0.5032298 ]
 [-0.46655148  0.5031603 ]
 [-0.46642357  0.50314486]
 [-0.4664505   0.5031602 ]
 [-0.46660858  0.5032597 ]
 [-0.46651924  0.5032276 ]
 [-0.4665075   0.5032901 ]
 [-0.4664924   0.5032829 ]
 [-0.46649158  0.5032788 ]
 [-0.46677178  0.50351626]
 [-0.46616727  0.5028536 ]
 [-0.46634585  0.50303316]
 [-0.46620607  0.5029445 ]
 [-0.4666763   0.5034264 ]
 [-0.46663886  0.5033933 ]
 [-0.4664585   0.5032381 ]
 [-0.46628428  0.5029706 ]
 [-0.4666618   0.5033119 ]
 [-0.46649718  0.5032003 ]
 [-0.46642047  0.50318104]
 [-0.46644086  0.50315714]
 

[[-0.4481671   0.48260128]
 [-0.44830728  0.48286006]
 [-0.44822037  0.48269477]
 [-0.44875586  0.48310694]
 [-0.44853276  0.48295885]
 [-0.4481309   0.48273185]
 [-0.44814342  0.48265418]
 [-0.4483788   0.48275015]
 [-0.44799614  0.4824498 ]
 [-0.4489408   0.48309526]
 [-0.4486633   0.48301363]
 [-0.4483828   0.48285857]
 [-0.4480319   0.48248   ]
 [-0.44820327  0.48276612]
 [-0.44886702  0.48316112]
 [-0.44827598  0.48274165]
 [-0.44843942  0.4828302 ]
 [-0.44806796  0.48253143]
 [-0.44852293  0.48282617]
 [-0.44774467  0.4822858 ]
 [-0.44845325  0.4829047 ]
 [-0.448281    0.4826329 ]
 [-0.44819146  0.48276058]
 [-0.4486853   0.48307738]
 [-0.44820076  0.48279878]
 [-0.44816822  0.48273277]
 [-0.44835413  0.48282126]
 [-0.44850475  0.4829212 ]
 [-0.44831115  0.48277113]
 [-0.44837457  0.48283502]
 [-0.44814718  0.48267764]
 [-0.44889045  0.48321688]
 [-0.44821954  0.4827528 ]
 [-0.44827944  0.4826695 ]
 [-0.44858938  0.48299053]
 [-0.44852626  0.48292857]
 [-0.44848937  0.48292276]
 

[[-0.35035738  0.37826622]
 [-0.35039616  0.3784724 ]
 [-0.35025123  0.37817782]
 [-0.35040432  0.3780564 ]
 [-0.3505016   0.3783717 ]
 [-0.35006374  0.37825722]
 [-0.3503952   0.378554  ]
 [-0.34986746  0.37748808]
 [-0.35011315  0.3782354 ]
 [-0.3499523   0.37692547]
 [-0.35048306  0.3778429 ]
 [-0.35072917  0.3788632 ]
 [-0.35008055  0.37827104]
 [-0.35019195  0.37811095]
 [-0.3501739   0.37738228]
 [-0.35017404  0.37813884]
 [-0.350252    0.37790838]
 [-0.35022658  0.37842584]
 [-0.35021126  0.3775667 ]
 [-0.34984607  0.37803277]
 [-0.35035458  0.37833023]
 [-0.35003757  0.37775064]
 [-0.35017085  0.37823075]
 [-0.34982696  0.37728238]
 [-0.3507174   0.37889552]
 [-0.34998322  0.37820533]
 [-0.35053778  0.37838835]
 [-0.35069478  0.37850666]
 [-0.35044637  0.37811998]
 [-0.35015357  0.37802377]
 [-0.3499151   0.37796748]
 [-0.35038662  0.3776064 ]
 [-0.35085106  0.37898004]
 [-0.34986034  0.377544  ]
 [-0.3505808   0.37816566]
 [-0.35019597  0.37775952]
 [-0.35028672  0.3780297 ]
 

KeyboardInterrupt: 

In [ ]:
def m_evaluate():
    trainer = Trainer(
        model=model,
        args=training_args,
        train_dataset=None,
        eval_dataset=tokenized_dataset["test"],
        data_collator=None,
        tokenizer=tokenizer,
        compute_metrics=compute_metrics,
    )
    result = trainer.evaluate()
    return result

m_evaluate()

## Q2

Efficient finetuning with adapter method.

1. Explain the adapter-based finetuning. You can also refer to the Adapter